version: '3.5'

services:
  mysql5.7:
    container_name: "mysql5.7"
    hostname: "mysql"
    image: "mysql:5.7"
    volumes:
      - ${BLOG_PATH}/Blog/docker/mysql/config:/etc/my.conf
      - ${BLOG_PATH}/Blog/docker/mysql/mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_DOCKER_PASSWORD}
      - TZ=Asia/Shanghai
    ports:
      - "3306:3306"
    networks: 
      - backend_db

  blog-app:
    container_name: "python3.5-uwsgi-blog-app"
    hostname: "blog-app"
    image: "registry.cn-hangzhou.aliyuncs.com/ilcyb/python-uwsgi:3.6.4"
    volumes:
      - ${BLOG_PATH}/Blog:/home/Blog
      - ${BLOG_PATH}/sockets:/home/socket
    environment:
      - MYSQL_USERNAME=${MYSQL_DOCKER_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_DOCKER_PASSWORD}
      - MYSQL_HOST=127.0.0.1
      - MYSQL_PORT=3306
      - TZ=Asia/Shanghai
      - MYSQL_HOST=mysql5.7
      - ENV=production
    ports:
      - "5000:5000"
    networks: 
      - backend_db
      - frontend
    command: "/var/uwsgi/uwsgi-2.0.17.1/uwsgi /home/Blog/docker/python3.5-uwsgi/uwsgi-app.ini"

  nginx:
    container_name: "nginx"
    hostname: "nginx"
    image: "nginx:1.15.2-alpine"
    volumes:
      - ${BLOG_PATH}/Blog:/var/www/Blog
      - ${BLOG_PATH}/Blog/docker/nginx/conf.d:/etc/nginx/conf.d
      - ${BLOG_PATH}/sockets:/home/socket
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "80:80"
      - "443:443"
    networks: 
      - frontend
    
networks:
  backend_db:
    driver: bridge
  frontend:
    driver: bridge