FROM alpine:3.8

COPY requirements.txt /home/requirements.txt

RUN apk add --no-cache python3 && \
    python3 -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip3 install --upgrade pip setuptools && \
    pip3 install uwsgi && \
    pip3 install -r /home/requirements.txt && \
    rm -r /root/.cache

EXPOSE 5000
EXPOSE 5001