FROM python:3.5.6

COPY requirements.txt /home/requirements.txt

RUN apt-get update && apt-get install -y \
    build-essential \
	python3 \
	python3-dev \
    python3-pip \
	wget && \
    apt-get autoremove && \
    rm -r /var/lib/apt/lists/* && \
    pip3 install --upgrade pip setuptools && \
    pip3 install -r /home/requirements.txt && \
    wget https://projects.unbit.it/downloads/uwsgi-2.0.17.1.tar.gz && \
    mkdir -p /var/uwsgi && \
    tar zxvf uwsgi-2.0.17.1.tar.gz -C /var/uwsgi && \
    cd /var/uwsgi/uwsgi-2.0.17.1 && \
    make

EXPOSE 5000
EXPOSE 5001